# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25d6b2ecca4b7c8cdf4eb7582292f285fc96345a579fa298081ee0f7f6a76567dcc37b108303269a1a5faf8b47bca707252e8496e99dd0995466f9aefddd9de5

test:
  secret_key_base: 18162557151d7bd3a656185edb325edaa0585d36a60cf077490bec6a2179dccc431da06f96301dea8db88c0638965ec2c832ea62a578529531a76674c786c934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
